# Generated by Django 4.1.1 on 2022-09-28 18:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeze_api', '0002_sequence_polycsdelay_sequence_polycsdist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='polyCsDelay',
            new_name='poly0Delay',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='polyCsDist',
            new_name='poly0Dist',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='polyCsFilter',
            new_name='poly0Filter',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='polyCsReverb',
            new_name='poly0Reverb',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='polyCsSynth',
            new_name='poly0Synth',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='polyCsVolume',
            new_name='poly0Volume',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='polyCsSteps',
        ),
        migrations.AddField(
            model_name='sequence',
            name='poly0Steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=10), null=True, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequence',
            name='poly1Delay',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='sequence',
            name='poly1Dist',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='sequence',
            name='poly1Filter',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='sequence',
            name='poly1Reverb',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='sequence',
            name='poly1Steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=11), null=True, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequence',
            name='poly1Synth',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sequence',
            name='poly1Volume',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sequence',
            name='poly2Delay',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='sequence',
            name='poly2Dist',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='sequence',
            name='poly2Filter',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='sequence',
            name='poly2Reverb',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='sequence',
            name='poly2Steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=11), null=True, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequence',
            name='poly2Synth',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sequence',
            name='poly2Volume',
            field=models.IntegerField(default=1),
        ),
    ]
