# Generated by Django 4.1.1 on 2022-09-29 15:49

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breeze_api', '0004_alter_sequence_poly0steps_alter_sequence_poly1steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='poly0Steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=10), null=True, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sequence',
            name='poly1Steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=11), null=True, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sequence',
            name='poly2Steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=11), null=True, size=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('password', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=48)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
